// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/job_dispatch.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface CancelJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.CancelJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool canceled = 1;</code>
   * @return The canceled.
   */
  boolean getCanceled();

  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 2;</code>
   * @return The error.
   */
  io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse getError();
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 2;</code>
   */
  io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder();
}
