// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/server_reconcile.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface CheckJobRunningRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.CheckJobRunningRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();
}
