// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/server_reconcile.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface CheckJobRunningResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.CheckJobRunningResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool running = 1;</code>
   * @return The running.
   */
  boolean getRunning();
}
