// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/data_fetcher.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public final class DataFetcherOuterClass {
  private DataFetcherOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ResultColumn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ResultColumn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ResultSchema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ResultSchema_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_FetchLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_FetchLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_FetchLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_FetchLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_FetchJobLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_FetchJobLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_FetchJobLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_FetchJobLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_PingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_PingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ClearJobLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ClearJobLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ClearJobLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ClearJobLogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033internal/data_fetcher.proto\022\021adhoc.int" +
      "ernal.v1\032\025internal/common.proto\"E\n\014Resul" +
      "tColumn\022\021\n\tcol_index\030\001 \001(\005\022\020\n\010col_name\030\002" +
      " \001(\t\022\020\n\010col_type\030\003 \001(\t\"@\n\014ResultSchema\0220" +
      "\n\007columns\030\001 \003(\0132\037.adhoc.internal.v1.Resu" +
      "ltColumn\"A\n\017FetchLogRequest\022\017\n\007task_id\030\001" +
      " \001(\t\022\016\n\006offset\030\002 \001(\003\022\r\n\005limit\030\003 \001(\005\"d\n\020F" +
      "etchLogResponse\022\r\n\005lines\030\001 \003(\t\022\020\n\010has_mo" +
      "re\030\002 \001(\010\022/\n\005error\030\003 \001(\0132 .adhoc.internal" +
      ".v1.ErrorResponse\"C\n\022FetchJobLogRequest\022" +
      "\016\n\006job_id\030\001 \001(\t\022\016\n\006offset\030\002 \001(\003\022\r\n\005limit" +
      "\030\003 \001(\005\"|\n\023FetchJobLogResponse\022\r\n\005lines\030\001" +
      " \003(\t\022\020\n\010has_more\030\002 \001(\010\022/\n\005error\030\003 \001(\0132 ." +
      "adhoc.internal.v1.ErrorResponse\022\023\n\013next_" +
      "offset\030\004 \001(\003\"\r\n\013PingRequest\"\032\n\014PingRespo" +
      "nse\022\n\n\002ok\030\001 \001(\010\"$\n\022ClearJobLogRequest\022\016\n" +
      "\006job_id\030\001 \001(\t\"\025\n\023ClearJobLogResponse2\347\002\n" +
      "\013DataFetcher\022S\n\010fetchLog\022\".adhoc.interna" +
      "l.v1.FetchLogRequest\032#.adhoc.internal.v1" +
      ".FetchLogResponse\022\\\n\013fetchJobLog\022%.adhoc" +
      ".internal.v1.FetchJobLogRequest\032&.adhoc." +
      "internal.v1.FetchJobLogResponse\022\\\n\013clear" +
      "JobLog\022%.adhoc.internal.v1.ClearJobLogRe" +
      "quest\032&.adhoc.internal.v1.ClearJobLogRes" +
      "ponse\022G\n\004ping\022\036.adhoc.internal.v1.PingRe" +
      "quest\032\037.adhoc.internal.v1.PingResponseB/" +
      "\n+io.gitee.songchaolin.adhoc.internal.gr" +
      "pc.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.gitee.songchaolin.adhoc.internal.grpc.v1.Common.getDescriptor(),
        });
    internal_static_adhoc_internal_v1_ResultColumn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_adhoc_internal_v1_ResultColumn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ResultColumn_descriptor,
        new java.lang.String[] { "ColIndex", "ColName", "ColType", });
    internal_static_adhoc_internal_v1_ResultSchema_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_adhoc_internal_v1_ResultSchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ResultSchema_descriptor,
        new java.lang.String[] { "Columns", });
    internal_static_adhoc_internal_v1_FetchLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_adhoc_internal_v1_FetchLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_FetchLogRequest_descriptor,
        new java.lang.String[] { "TaskId", "Offset", "Limit", });
    internal_static_adhoc_internal_v1_FetchLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_adhoc_internal_v1_FetchLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_FetchLogResponse_descriptor,
        new java.lang.String[] { "Lines", "HasMore", "Error", });
    internal_static_adhoc_internal_v1_FetchJobLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_adhoc_internal_v1_FetchJobLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_FetchJobLogRequest_descriptor,
        new java.lang.String[] { "JobId", "Offset", "Limit", });
    internal_static_adhoc_internal_v1_FetchJobLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_adhoc_internal_v1_FetchJobLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_FetchJobLogResponse_descriptor,
        new java.lang.String[] { "Lines", "HasMore", "Error", "NextOffset", });
    internal_static_adhoc_internal_v1_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_adhoc_internal_v1_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_PingRequest_descriptor,
        new java.lang.String[] { });
    internal_static_adhoc_internal_v1_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_adhoc_internal_v1_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_PingResponse_descriptor,
        new java.lang.String[] { "Ok", });
    internal_static_adhoc_internal_v1_ClearJobLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_adhoc_internal_v1_ClearJobLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ClearJobLogRequest_descriptor,
        new java.lang.String[] { "JobId", });
    internal_static_adhoc_internal_v1_ClearJobLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_adhoc_internal_v1_ClearJobLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ClearJobLogResponse_descriptor,
        new java.lang.String[] { });
    io.gitee.songchaolin.adhoc.internal.grpc.v1.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
