// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/job_dispatch.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface DispatchJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.DispatchJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string user_name = 3;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 3;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <pre>
   * KYUUBI / STARROCKS
   * </pre>
   *
   * <code>string engine_type = 4;</code>
   * @return The engineType.
   */
  java.lang.String getEngineType();
  /**
   * <pre>
   * KYUUBI / STARROCKS
   * </pre>
   *
   * <code>string engine_type = 4;</code>
   * @return The bytes for engineType.
   */
  com.google.protobuf.ByteString
      getEngineTypeBytes();

  /**
   * <code>string engine_instance = 5;</code>
   * @return The engineInstance.
   */
  java.lang.String getEngineInstance();
  /**
   * <code>string engine_instance = 5;</code>
   * @return The bytes for engineInstance.
   */
  com.google.protobuf.ByteString
      getEngineInstanceBytes();

  /**
   * <code>string sql_content = 6;</code>
   * @return The sqlContent.
   */
  java.lang.String getSqlContent();
  /**
   * <code>string sql_content = 6;</code>
   * @return The bytes for sqlContent.
   */
  com.google.protobuf.ByteString
      getSqlContentBytes();

  /**
   * <code>string client_request_id = 7;</code>
   * @return The clientRequestId.
   */
  java.lang.String getClientRequestId();
  /**
   * <code>string client_request_id = 7;</code>
   * @return The bytes for clientRequestId.
   */
  com.google.protobuf.ByteString
      getClientRequestIdBytes();

  /**
   * <code>string server_instance_id = 8;</code>
   * @return The serverInstanceId.
   */
  java.lang.String getServerInstanceId();
  /**
   * <code>string server_instance_id = 8;</code>
   * @return The bytes for serverInstanceId.
   */
  com.google.protobuf.ByteString
      getServerInstanceIdBytes();
}
