// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/common.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error_code = 1;</code>
   * @return The errorCode.
   */
  java.lang.String getErrorCode();
  /**
   * <code>string error_code = 1;</code>
   * @return The bytes for errorCode.
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <code>string error_message = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
