// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/data_fetcher.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface FetchLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.FetchLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>int64 offset = 2;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>int32 limit = 3;</code>
   * @return The limit.
   */
  int getLimit();
}
