// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/data_fetcher.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

/**
 * Protobuf type {@code adhoc.internal.v1.FetchJobLogResponse}
 */
public final class FetchJobLogResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:adhoc.internal.v1.FetchJobLogResponse)
    FetchJobLogResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchJobLogResponse.newBuilder() to construct.
  private FetchJobLogResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchJobLogResponse() {
    lines_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FetchJobLogResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.gitee.songchaolin.adhoc.internal.grpc.v1.DataFetcherOuterClass.internal_static_adhoc_internal_v1_FetchJobLogResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.gitee.songchaolin.adhoc.internal.grpc.v1.DataFetcherOuterClass.internal_static_adhoc_internal_v1_FetchJobLogResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse.class, io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse.Builder.class);
  }

  public static final int LINES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList lines_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string lines = 1;</code>
   * @return A list containing the lines.
   */
  public com.google.protobuf.ProtocolStringList
      getLinesList() {
    return lines_;
  }
  /**
   * <code>repeated string lines = 1;</code>
   * @return The count of lines.
   */
  public int getLinesCount() {
    return lines_.size();
  }
  /**
   * <code>repeated string lines = 1;</code>
   * @param index The index of the element to return.
   * @return The lines at the given index.
   */
  public java.lang.String getLines(int index) {
    return lines_.get(index);
  }
  /**
   * <code>repeated string lines = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the lines at the given index.
   */
  public com.google.protobuf.ByteString
      getLinesBytes(int index) {
    return lines_.getByteString(index);
  }

  public static final int HAS_MORE_FIELD_NUMBER = 2;
  private boolean hasMore_ = false;
  /**
   * <code>bool has_more = 2;</code>
   * @return The hasMore.
   */
  @java.lang.Override
  public boolean getHasMore() {
    return hasMore_;
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  private io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse error_;
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   * @return The error.
   */
  @java.lang.Override
  public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse getError() {
    return error_ == null ? io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
  }
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   */
  @java.lang.Override
  public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder() {
    return error_ == null ? io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
  }

  public static final int NEXT_OFFSET_FIELD_NUMBER = 4;
  private long nextOffset_ = 0L;
  /**
   * <pre>
   * 下次应读的全局 offset（eviction 后 server 据此调整 lastPulledOffset，防永久空拉）
   * </pre>
   *
   * <code>int64 next_offset = 4;</code>
   * @return The nextOffset.
   */
  @java.lang.Override
  public long getNextOffset() {
    return nextOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < lines_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lines_.getRaw(i));
    }
    if (hasMore_ != false) {
      output.writeBool(2, hasMore_);
    }
    if (error_ != null) {
      output.writeMessage(3, getError());
    }
    if (nextOffset_ != 0L) {
      output.writeInt64(4, nextOffset_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < lines_.size(); i++) {
        dataSize += computeStringSizeNoTag(lines_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLinesList().size();
    }
    if (hasMore_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hasMore_);
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getError());
    }
    if (nextOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, nextOffset_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse)) {
      return super.equals(obj);
    }
    io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse other = (io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse) obj;

    if (!getLinesList()
        .equals(other.getLinesList())) return false;
    if (getHasMore()
        != other.getHasMore()) return false;
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (getNextOffset()
        != other.getNextOffset()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLinesCount() > 0) {
      hash = (37 * hash) + LINES_FIELD_NUMBER;
      hash = (53 * hash) + getLinesList().hashCode();
    }
    hash = (37 * hash) + HAS_MORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasMore());
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (37 * hash) + NEXT_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNextOffset());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code adhoc.internal.v1.FetchJobLogResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:adhoc.internal.v1.FetchJobLogResponse)
      io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.DataFetcherOuterClass.internal_static_adhoc_internal_v1_FetchJobLogResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.DataFetcherOuterClass.internal_static_adhoc_internal_v1_FetchJobLogResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse.class, io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse.Builder.class);
    }

    // Construct using io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lines_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      hasMore_ = false;
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      nextOffset_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.DataFetcherOuterClass.internal_static_adhoc_internal_v1_FetchJobLogResponse_descriptor;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse getDefaultInstanceForType() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse build() {
      io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse buildPartial() {
      io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse result = new io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        lines_.makeImmutable();
        result.lines_ = lines_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hasMore_ = hasMore_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.nextOffset_ = nextOffset_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse) {
        return mergeFrom((io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse other) {
      if (other == io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse.getDefaultInstance()) return this;
      if (!other.lines_.isEmpty()) {
        if (lines_.isEmpty()) {
          lines_ = other.lines_;
          bitField0_ |= 0x00000001;
        } else {
          ensureLinesIsMutable();
          lines_.addAll(other.lines_);
        }
        onChanged();
      }
      if (other.getHasMore() != false) {
        setHasMore(other.getHasMore());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (other.getNextOffset() != 0L) {
        setNextOffset(other.getNextOffset());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLinesIsMutable();
              lines_.add(s);
              break;
            } // case 10
            case 16: {
              hasMore_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              nextOffset_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList lines_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLinesIsMutable() {
      if (!lines_.isModifiable()) {
        lines_ = new com.google.protobuf.LazyStringArrayList(lines_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @return A list containing the lines.
     */
    public com.google.protobuf.ProtocolStringList
        getLinesList() {
      lines_.makeImmutable();
      return lines_;
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @return The count of lines.
     */
    public int getLinesCount() {
      return lines_.size();
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @param index The index of the element to return.
     * @return The lines at the given index.
     */
    public java.lang.String getLines(int index) {
      return lines_.get(index);
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the lines at the given index.
     */
    public com.google.protobuf.ByteString
        getLinesBytes(int index) {
      return lines_.getByteString(index);
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @param index The index to set the value at.
     * @param value The lines to set.
     * @return This builder for chaining.
     */
    public Builder setLines(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinesIsMutable();
      lines_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @param value The lines to add.
     * @return This builder for chaining.
     */
    public Builder addLines(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinesIsMutable();
      lines_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @param values The lines to add.
     * @return This builder for chaining.
     */
    public Builder addAllLines(
        java.lang.Iterable<java.lang.String> values) {
      ensureLinesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, lines_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLines() {
      lines_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string lines = 1;</code>
     * @param value The bytes of the lines to add.
     * @return This builder for chaining.
     */
    public Builder addLinesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLinesIsMutable();
      lines_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean hasMore_ ;
    /**
     * <code>bool has_more = 2;</code>
     * @return The hasMore.
     */
    @java.lang.Override
    public boolean getHasMore() {
      return hasMore_;
    }
    /**
     * <code>bool has_more = 2;</code>
     * @param value The hasMore to set.
     * @return This builder for chaining.
     */
    public Builder setHasMore(boolean value) {

      hasMore_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_more = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasMore() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hasMore_ = false;
      onChanged();
      return this;
    }

    private io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder> errorBuilder_;
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     * @return The error.
     */
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public Builder setError(io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public Builder setError(
        io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public Builder mergeError(io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          error_ != null &&
          error_ != io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000004);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder getErrorBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private long nextOffset_ ;
    /**
     * <pre>
     * 下次应读的全局 offset（eviction 后 server 据此调整 lastPulledOffset，防永久空拉）
     * </pre>
     *
     * <code>int64 next_offset = 4;</code>
     * @return The nextOffset.
     */
    @java.lang.Override
    public long getNextOffset() {
      return nextOffset_;
    }
    /**
     * <pre>
     * 下次应读的全局 offset（eviction 后 server 据此调整 lastPulledOffset，防永久空拉）
     * </pre>
     *
     * <code>int64 next_offset = 4;</code>
     * @param value The nextOffset to set.
     * @return This builder for chaining.
     */
    public Builder setNextOffset(long value) {

      nextOffset_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 下次应读的全局 offset（eviction 后 server 据此调整 lastPulledOffset，防永久空拉）
     * </pre>
     *
     * <code>int64 next_offset = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextOffset() {
      bitField0_ = (bitField0_ & ~0x00000008);
      nextOffset_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:adhoc.internal.v1.FetchJobLogResponse)
  }

  // @@protoc_insertion_point(class_scope:adhoc.internal.v1.FetchJobLogResponse)
  private static final io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse();
  }

  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchJobLogResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchJobLogResponse>() {
    @java.lang.Override
    public FetchJobLogResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FetchJobLogResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchJobLogResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.gitee.songchaolin.adhoc.internal.grpc.v1.FetchJobLogResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

