// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/job_dispatch.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface GetRunningJobsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.GetRunningJobsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string job_ids = 1;</code>
   * @return A list containing the jobIds.
   */
  java.util.List<java.lang.String>
      getJobIdsList();
  /**
   * <code>repeated string job_ids = 1;</code>
   * @return The count of jobIds.
   */
  int getJobIdsCount();
  /**
   * <code>repeated string job_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The jobIds at the given index.
   */
  java.lang.String getJobIds(int index);
  /**
   * <code>repeated string job_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the jobIds at the given index.
   */
  com.google.protobuf.ByteString
      getJobIdsBytes(int index);
}
