// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/job_dispatch.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

/**
 * Protobuf type {@code adhoc.internal.v1.GetRunningJobsResponse}
 */
public final class GetRunningJobsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:adhoc.internal.v1.GetRunningJobsResponse)
    GetRunningJobsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetRunningJobsResponse.newBuilder() to construct.
  private GetRunningJobsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetRunningJobsResponse() {
    jobIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetRunningJobsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.gitee.songchaolin.adhoc.internal.grpc.v1.JobDispatch.internal_static_adhoc_internal_v1_GetRunningJobsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.gitee.songchaolin.adhoc.internal.grpc.v1.JobDispatch.internal_static_adhoc_internal_v1_GetRunningJobsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse.class, io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse.Builder.class);
  }

  public static final int JOB_IDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList jobIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string job_ids = 1;</code>
   * @return A list containing the jobIds.
   */
  public com.google.protobuf.ProtocolStringList
      getJobIdsList() {
    return jobIds_;
  }
  /**
   * <code>repeated string job_ids = 1;</code>
   * @return The count of jobIds.
   */
  public int getJobIdsCount() {
    return jobIds_.size();
  }
  /**
   * <code>repeated string job_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The jobIds at the given index.
   */
  public java.lang.String getJobIds(int index) {
    return jobIds_.get(index);
  }
  /**
   * <code>repeated string job_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the jobIds at the given index.
   */
  public com.google.protobuf.ByteString
      getJobIdsBytes(int index) {
    return jobIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jobIds_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < jobIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(jobIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getJobIdsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse)) {
      return super.equals(obj);
    }
    io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse other = (io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse) obj;

    if (!getJobIdsList()
        .equals(other.getJobIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobIdsCount() > 0) {
      hash = (37 * hash) + JOB_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getJobIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code adhoc.internal.v1.GetRunningJobsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:adhoc.internal.v1.GetRunningJobsResponse)
      io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.JobDispatch.internal_static_adhoc_internal_v1_GetRunningJobsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.JobDispatch.internal_static_adhoc_internal_v1_GetRunningJobsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse.class, io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse.Builder.class);
    }

    // Construct using io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      jobIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.JobDispatch.internal_static_adhoc_internal_v1_GetRunningJobsResponse_descriptor;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse getDefaultInstanceForType() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse build() {
      io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse buildPartial() {
      io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse result = new io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        jobIds_.makeImmutable();
        result.jobIds_ = jobIds_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse) {
        return mergeFrom((io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse other) {
      if (other == io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse.getDefaultInstance()) return this;
      if (!other.jobIds_.isEmpty()) {
        if (jobIds_.isEmpty()) {
          jobIds_ = other.jobIds_;
          bitField0_ |= 0x00000001;
        } else {
          ensureJobIdsIsMutable();
          jobIds_.addAll(other.jobIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureJobIdsIsMutable();
              jobIds_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList jobIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureJobIdsIsMutable() {
      if (!jobIds_.isModifiable()) {
        jobIds_ = new com.google.protobuf.LazyStringArrayList(jobIds_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @return A list containing the jobIds.
     */
    public com.google.protobuf.ProtocolStringList
        getJobIdsList() {
      jobIds_.makeImmutable();
      return jobIds_;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @return The count of jobIds.
     */
    public int getJobIdsCount() {
      return jobIds_.size();
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The jobIds at the given index.
     */
    public java.lang.String getJobIds(int index) {
      return jobIds_.get(index);
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the jobIds at the given index.
     */
    public com.google.protobuf.ByteString
        getJobIdsBytes(int index) {
      return jobIds_.getByteString(index);
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param index The index to set the value at.
     * @param value The jobIds to set.
     * @return This builder for chaining.
     */
    public Builder setJobIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureJobIdsIsMutable();
      jobIds_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param value The jobIds to add.
     * @return This builder for chaining.
     */
    public Builder addJobIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureJobIdsIsMutable();
      jobIds_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param values The jobIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllJobIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureJobIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, jobIds_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobIds() {
      jobIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string job_ids = 1;</code>
     * @param value The bytes of the jobIds to add.
     * @return This builder for chaining.
     */
    public Builder addJobIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureJobIdsIsMutable();
      jobIds_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:adhoc.internal.v1.GetRunningJobsResponse)
  }

  // @@protoc_insertion_point(class_scope:adhoc.internal.v1.GetRunningJobsResponse)
  private static final io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse();
  }

  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRunningJobsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetRunningJobsResponse>() {
    @java.lang.Override
    public GetRunningJobsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetRunningJobsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRunningJobsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.gitee.songchaolin.adhoc.internal.grpc.v1.GetRunningJobsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

