// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/heartbeat.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

/**
 * Protobuf type {@code adhoc.internal.v1.HeartbeatResponse}
 */
public final class HeartbeatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:adhoc.internal.v1.HeartbeatResponse)
    HeartbeatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartbeatResponse.newBuilder() to construct.
  private HeartbeatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartbeatResponse() {
    action_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeartbeatResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.gitee.songchaolin.adhoc.internal.grpc.v1.Heartbeat.internal_static_adhoc_internal_v1_HeartbeatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.gitee.songchaolin.adhoc.internal.grpc.v1.Heartbeat.internal_static_adhoc_internal_v1_HeartbeatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse.class, io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse.Builder.class);
  }

  public static final int ACCEPTED_FIELD_NUMBER = 1;
  private boolean accepted_ = false;
  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  @java.lang.Override
  public boolean getAccepted() {
    return accepted_;
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object action_ = "";
  /**
   * <pre>
   * NONE / DRAIN
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * NONE / DRAIN
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  private io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse error_;
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   * @return The error.
   */
  @java.lang.Override
  public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse getError() {
    return error_ == null ? io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
  }
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   */
  @java.lang.Override
  public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder() {
    return error_ == null ? io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (accepted_ != false) {
      output.writeBool(1, accepted_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, action_);
    }
    if (error_ != null) {
      output.writeMessage(3, getError());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (accepted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, accepted_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, action_);
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getError());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse)) {
      return super.equals(obj);
    }
    io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse other = (io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse) obj;

    if (getAccepted()
        != other.getAccepted()) return false;
    if (!getAction()
        .equals(other.getAction())) return false;
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCEPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAccepted());
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code adhoc.internal.v1.HeartbeatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:adhoc.internal.v1.HeartbeatResponse)
      io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.Heartbeat.internal_static_adhoc_internal_v1_HeartbeatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.Heartbeat.internal_static_adhoc_internal_v1_HeartbeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse.class, io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse.Builder.class);
    }

    // Construct using io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accepted_ = false;
      action_ = "";
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.Heartbeat.internal_static_adhoc_internal_v1_HeartbeatResponse_descriptor;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse getDefaultInstanceForType() {
      return io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse build() {
      io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse buildPartial() {
      io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse result = new io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accepted_ = accepted_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.action_ = action_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse) {
        return mergeFrom((io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse other) {
      if (other == io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse.getDefaultInstance()) return this;
      if (other.getAccepted() != false) {
        setAccepted(other.getAccepted());
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              accepted_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              action_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean accepted_ ;
    /**
     * <code>bool accepted = 1;</code>
     * @return The accepted.
     */
    @java.lang.Override
    public boolean getAccepted() {
      return accepted_;
    }
    /**
     * <code>bool accepted = 1;</code>
     * @param value The accepted to set.
     * @return This builder for chaining.
     */
    public Builder setAccepted(boolean value) {

      accepted_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool accepted = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccepted() {
      bitField0_ = (bitField0_ & ~0x00000001);
      accepted_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <pre>
     * NONE / DRAIN
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * NONE / DRAIN
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * NONE / DRAIN
     * </pre>
     *
     * <code>string action = 2;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      action_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * NONE / DRAIN
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      action_ = getDefaultInstance().getAction();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * NONE / DRAIN
     * </pre>
     *
     * <code>string action = 2;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      action_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder> errorBuilder_;
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     * @return The error.
     */
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public Builder setError(io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public Builder setError(
        io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public Builder mergeError(io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          error_ != null &&
          error_ != io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000004);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder getErrorBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    public io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:adhoc.internal.v1.HeartbeatResponse)
  }

  // @@protoc_insertion_point(class_scope:adhoc.internal.v1.HeartbeatResponse)
  private static final io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse();
  }

  public static io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartbeatResponse>
      PARSER = new com.google.protobuf.AbstractParser<HeartbeatResponse>() {
    @java.lang.Override
    public HeartbeatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HeartbeatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartbeatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.gitee.songchaolin.adhoc.internal.grpc.v1.HeartbeatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

