// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/heartbeat.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <pre>
   * NONE / DRAIN
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * NONE / DRAIN
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   * @return The error.
   */
  io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse getError();
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 3;</code>
   */
  io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder();
}
