// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/job_dispatch.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public final class JobDispatch {
  private JobDispatch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_DispatchJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_DispatchJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_DispatchJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_DispatchJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_CancelJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_CancelJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_CancelJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_CancelJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_GetRunningJobsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_GetRunningJobsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_GetRunningJobsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_GetRunningJobsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033internal/job_dispatch.proto\022\021adhoc.int" +
      "ernal.v1\032\025internal/common.proto\"\302\001\n\022Disp" +
      "atchJobRequest\022\016\n\006job_id\030\001 \001(\t\022\017\n\007user_i" +
      "d\030\002 \001(\t\022\021\n\tuser_name\030\003 \001(\t\022\023\n\013engine_typ" +
      "e\030\004 \001(\t\022\027\n\017engine_instance\030\005 \001(\t\022\023\n\013sql_" +
      "content\030\006 \001(\t\022\031\n\021client_request_id\030\007 \001(\t" +
      "\022\032\n\022server_instance_id\030\010 \001(\t\"X\n\023Dispatch" +
      "JobResponse\022\020\n\010accepted\030\001 \001(\010\022/\n\005error\030\002" +
      " \001(\0132 .adhoc.internal.v1.ErrorResponse\"\"" +
      "\n\020CancelJobRequest\022\016\n\006job_id\030\001 \001(\t\"V\n\021Ca" +
      "ncelJobResponse\022\020\n\010canceled\030\001 \001(\010\022/\n\005err" +
      "or\030\002 \001(\0132 .adhoc.internal.v1.ErrorRespon" +
      "se\"\027\n\025GetRunningJobsRequest\")\n\026GetRunnin" +
      "gJobsResponse\022\017\n\007job_ids\030\001 \003(\t2k\n\013JobExe" +
      "cutor\022\\\n\013dispatchJob\022%.adhoc.internal.v1" +
      ".DispatchJobRequest\032&.adhoc.internal.v1." +
      "DispatchJobResponse2\313\001\n\nJobManager\022V\n\tca" +
      "ncelJob\022#.adhoc.internal.v1.CancelJobReq" +
      "uest\032$.adhoc.internal.v1.CancelJobRespon" +
      "se\022e\n\016getRunningJobs\022(.adhoc.internal.v1" +
      ".GetRunningJobsRequest\032).adhoc.internal." +
      "v1.GetRunningJobsResponseB/\n+io.gitee.so" +
      "ngchaolin.adhoc.internal.grpc.v1P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.gitee.songchaolin.adhoc.internal.grpc.v1.Common.getDescriptor(),
        });
    internal_static_adhoc_internal_v1_DispatchJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_adhoc_internal_v1_DispatchJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_DispatchJobRequest_descriptor,
        new java.lang.String[] { "JobId", "UserId", "UserName", "EngineType", "EngineInstance", "SqlContent", "ClientRequestId", "ServerInstanceId", });
    internal_static_adhoc_internal_v1_DispatchJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_adhoc_internal_v1_DispatchJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_DispatchJobResponse_descriptor,
        new java.lang.String[] { "Accepted", "Error", });
    internal_static_adhoc_internal_v1_CancelJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_adhoc_internal_v1_CancelJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_CancelJobRequest_descriptor,
        new java.lang.String[] { "JobId", });
    internal_static_adhoc_internal_v1_CancelJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_adhoc_internal_v1_CancelJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_CancelJobResponse_descriptor,
        new java.lang.String[] { "Canceled", "Error", });
    internal_static_adhoc_internal_v1_GetRunningJobsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_adhoc_internal_v1_GetRunningJobsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_GetRunningJobsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_adhoc_internal_v1_GetRunningJobsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_adhoc_internal_v1_GetRunningJobsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_GetRunningJobsResponse_descriptor,
        new java.lang.String[] { "JobIds", });
    io.gitee.songchaolin.adhoc.internal.grpc.v1.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
