// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/status_report.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface ReportJobStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.ReportJobStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool applied = 1;</code>
   * @return The applied.
   */
  boolean getApplied();

  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 2;</code>
   * @return The error.
   */
  io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponse getError();
  /**
   * <code>.adhoc.internal.v1.ErrorResponse error = 2;</code>
   */
  io.gitee.songchaolin.adhoc.internal.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder();
}
