// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/data_fetcher.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface ResultSchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.ResultSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .adhoc.internal.v1.ResultColumn columns = 1;</code>
   */
  java.util.List<io.gitee.songchaolin.adhoc.internal.grpc.v1.ResultColumn> 
      getColumnsList();
  /**
   * <code>repeated .adhoc.internal.v1.ResultColumn columns = 1;</code>
   */
  io.gitee.songchaolin.adhoc.internal.grpc.v1.ResultColumn getColumns(int index);
  /**
   * <code>repeated .adhoc.internal.v1.ResultColumn columns = 1;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .adhoc.internal.v1.ResultColumn columns = 1;</code>
   */
  java.util.List<? extends io.gitee.songchaolin.adhoc.internal.grpc.v1.ResultColumnOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .adhoc.internal.v1.ResultColumn columns = 1;</code>
   */
  io.gitee.songchaolin.adhoc.internal.grpc.v1.ResultColumnOrBuilder getColumnsOrBuilder(
      int index);
}
