// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/server_reconcile.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public final class ServerReconcile {
  private ServerReconcile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_CheckJobRunningRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_CheckJobRunningRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_CheckJobRunningResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_CheckJobRunningResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ServerJobLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ServerJobLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ServerJobLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ServerJobLogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037internal/server_reconcile.proto\022\021adhoc" +
      ".internal.v1\032\025internal/common.proto\"(\n\026C" +
      "heckJobRunningRequest\022\016\n\006job_id\030\001 \001(\t\"*\n" +
      "\027CheckJobRunningResponse\022\017\n\007running\030\001 \001(" +
      "\010\"D\n\023ServerJobLogRequest\022\016\n\006job_id\030\001 \001(\t" +
      "\022\016\n\006offset\030\002 \001(\003\022\r\n\005limit\030\003 \001(\005\"X\n\024Serve" +
      "rJobLogResponse\022\r\n\005lines\030\001 \003(\t\022\020\n\010has_mo" +
      "re\030\002 \001(\010\022\r\n\005found\030\003 \001(\010\022\020\n\010complete\030\004 \001(" +
      "\0102\342\001\n\026ServerReconcileService\022h\n\017checkJob" +
      "Running\022).adhoc.internal.v1.CheckJobRunn" +
      "ingRequest\032*.adhoc.internal.v1.CheckJobR" +
      "unningResponse\022^\n\013fetchJobLog\022&.adhoc.in" +
      "ternal.v1.ServerJobLogRequest\032\'.adhoc.in" +
      "ternal.v1.ServerJobLogResponseB/\n+io.git" +
      "ee.songchaolin.adhoc.internal.grpc.v1P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.gitee.songchaolin.adhoc.internal.grpc.v1.Common.getDescriptor(),
        });
    internal_static_adhoc_internal_v1_CheckJobRunningRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_adhoc_internal_v1_CheckJobRunningRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_CheckJobRunningRequest_descriptor,
        new java.lang.String[] { "JobId", });
    internal_static_adhoc_internal_v1_CheckJobRunningResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_adhoc_internal_v1_CheckJobRunningResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_CheckJobRunningResponse_descriptor,
        new java.lang.String[] { "Running", });
    internal_static_adhoc_internal_v1_ServerJobLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_adhoc_internal_v1_ServerJobLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ServerJobLogRequest_descriptor,
        new java.lang.String[] { "JobId", "Offset", "Limit", });
    internal_static_adhoc_internal_v1_ServerJobLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_adhoc_internal_v1_ServerJobLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ServerJobLogResponse_descriptor,
        new java.lang.String[] { "Lines", "HasMore", "Found", "Complete", });
    io.gitee.songchaolin.adhoc.internal.grpc.v1.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
