// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/server_reconcile.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public interface ServerJobLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.internal.v1.ServerJobLogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string lines = 1;</code>
   * @return A list containing the lines.
   */
  java.util.List<java.lang.String>
      getLinesList();
  /**
   * <code>repeated string lines = 1;</code>
   * @return The count of lines.
   */
  int getLinesCount();
  /**
   * <code>repeated string lines = 1;</code>
   * @param index The index of the element to return.
   * @return The lines at the given index.
   */
  java.lang.String getLines(int index);
  /**
   * <code>repeated string lines = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the lines at the given index.
   */
  com.google.protobuf.ByteString
      getLinesBytes(int index);

  /**
   * <code>bool has_more = 2;</code>
   * @return The hasMore.
   */
  boolean getHasMore();

  /**
   * <pre>
   * 本节点是否有该 job 日志（false=不在本节点/已清理，调用方 fallback OSS）
   * </pre>
   *
   * <code>bool found = 3;</code>
   * @return The found.
   */
  boolean getFound();

  /**
   * <pre>
   * 日志是否已完整（终态）：转发方据本节点 registry 快照判断
   * </pre>
   *
   * <code>bool complete = 4;</code>
   * @return The complete.
   */
  boolean getComplete();
}
