// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/status_report.proto

package io.gitee.songchaolin.adhoc.internal.grpc.v1;

public final class StatusReport {
  private StatusReport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ReportTaskStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ReportTaskStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ReportTaskStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ReportTaskStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ReportJobStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ReportJobStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_internal_v1_ReportJobStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_internal_v1_ReportJobStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034internal/status_report.proto\022\021adhoc.in" +
      "ternal.v1\032\025internal/common.proto\"\246\001\n\027Rep" +
      "ortTaskStatusRequest\022\017\n\007task_id\030\001 \001(\t\022\016\n" +
      "\006status\030\002 \001(\t\022\r\n\005stage\030\003 \001(\t\022\022\n\nfail_sta" +
      "ge\030\004 \001(\t\022\034\n\024fail_reason_category\030\005 \001(\t\022\022" +
      "\n\nerror_code\030\006 \001(\t\022\025\n\rerror_message\030\007 \001(" +
      "\t\"\\\n\030ReportTaskStatusResponse\022\017\n\007applied" +
      "\030\001 \001(\010\022/\n\005error\030\002 \001(\0132 .adhoc.internal.v" +
      "1.ErrorResponse\"c\n\026ReportJobStatusReques" +
      "t\022\016\n\006job_id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022\022\n\nerr" +
      "or_code\030\003 \001(\t\022\025\n\rerror_message\030\004 \001(\t\"[\n\027" +
      "ReportJobStatusResponse\022\017\n\007applied\030\001 \001(\010" +
      "\022/\n\005error\030\002 \001(\0132 .adhoc.internal.v1.Erro" +
      "rResponse2\200\001\n\021TaskStatusService\022k\n\020repor" +
      "tTaskStatus\022*.adhoc.internal.v1.ReportTa" +
      "skStatusRequest\032+.adhoc.internal.v1.Repo" +
      "rtTaskStatusResponse2|\n\020JobStatusService" +
      "\022h\n\017reportJobStatus\022).adhoc.internal.v1." +
      "ReportJobStatusRequest\032*.adhoc.internal." +
      "v1.ReportJobStatusResponseB/\n+io.gitee.s" +
      "ongchaolin.adhoc.internal.grpc.v1P\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.gitee.songchaolin.adhoc.internal.grpc.v1.Common.getDescriptor(),
        });
    internal_static_adhoc_internal_v1_ReportTaskStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_adhoc_internal_v1_ReportTaskStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ReportTaskStatusRequest_descriptor,
        new java.lang.String[] { "TaskId", "Status", "Stage", "FailStage", "FailReasonCategory", "ErrorCode", "ErrorMessage", });
    internal_static_adhoc_internal_v1_ReportTaskStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_adhoc_internal_v1_ReportTaskStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ReportTaskStatusResponse_descriptor,
        new java.lang.String[] { "Applied", "Error", });
    internal_static_adhoc_internal_v1_ReportJobStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_adhoc_internal_v1_ReportJobStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ReportJobStatusRequest_descriptor,
        new java.lang.String[] { "JobId", "Status", "ErrorCode", "ErrorMessage", });
    internal_static_adhoc_internal_v1_ReportJobStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_adhoc_internal_v1_ReportJobStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_internal_v1_ReportJobStatusResponse_descriptor,
        new java.lang.String[] { "Applied", "Error", });
    io.gitee.songchaolin.adhoc.internal.grpc.v1.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
