// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

/**
 * <pre>
 **
 * 取消 Job 响应
 * </pre>
 *
 * Protobuf type {@code adhoc.sdk.v1.CancelJobResponse}
 */
public final class CancelJobResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:adhoc.sdk.v1.CancelJobResponse)
    CancelJobResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CancelJobResponse.newBuilder() to construct.
  private CancelJobResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CancelJobResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CancelJobResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_CancelJobResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_CancelJobResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse.class, io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse.Builder.class);
  }

  public static final int CANCELED_FIELD_NUMBER = 1;
  private boolean canceled_ = false;
  /**
   * <code>bool canceled = 1;</code>
   * @return The canceled.
   */
  @java.lang.Override
  public boolean getCanceled() {
    return canceled_;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse error_;
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse getError() {
    return error_ == null ? io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
  }
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   */
  @java.lang.Override
  public io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder() {
    return error_ == null ? io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (canceled_ != false) {
      output.writeBool(1, canceled_);
    }
    if (error_ != null) {
      output.writeMessage(2, getError());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (canceled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, canceled_);
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse)) {
      return super.equals(obj);
    }
    io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse other = (io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse) obj;

    if (getCanceled()
        != other.getCanceled()) return false;
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CANCELED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanceled());
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 取消 Job 响应
   * </pre>
   *
   * Protobuf type {@code adhoc.sdk.v1.CancelJobResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:adhoc.sdk.v1.CancelJobResponse)
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_CancelJobResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_CancelJobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse.class, io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse.Builder.class);
    }

    // Construct using io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      canceled_ = false;
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_CancelJobResponse_descriptor;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse getDefaultInstanceForType() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse build() {
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse buildPartial() {
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse result = new io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.canceled_ = canceled_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse) {
        return mergeFrom((io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse other) {
      if (other == io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse.getDefaultInstance()) return this;
      if (other.getCanceled() != false) {
        setCanceled(other.getCanceled());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              canceled_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean canceled_ ;
    /**
     * <code>bool canceled = 1;</code>
     * @return The canceled.
     */
    @java.lang.Override
    public boolean getCanceled() {
      return canceled_;
    }
    /**
     * <code>bool canceled = 1;</code>
     * @param value The canceled to set.
     * @return This builder for chaining.
     */
    public Builder setCanceled(boolean value) {

      canceled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool canceled = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanceled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      canceled_ = false;
      onChanged();
      return this;
    }

    private io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder> errorBuilder_;
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     * @return The error.
     */
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     */
    public Builder setError(io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     */
    public Builder setError(
        io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     */
    public Builder mergeError(io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          error_ != null &&
          error_ != io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000002);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     */
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.Builder getErrorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     */
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse, io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse.Builder, io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:adhoc.sdk.v1.CancelJobResponse)
  }

  // @@protoc_insertion_point(class_scope:adhoc.sdk.v1.CancelJobResponse)
  private static final io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse();
  }

  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CancelJobResponse>
      PARSER = new com.google.protobuf.AbstractParser<CancelJobResponse>() {
    @java.lang.Override
    public CancelJobResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CancelJobResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CancelJobResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.gitee.songchaolin.adhoc.sdk.grpc.v1.CancelJobResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

