// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface ColumnSchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.ColumnSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 col_index = 1;</code>
   * @return The colIndex.
   */
  int getColIndex();

  /**
   * <code>string col_name = 2;</code>
   * @return The colName.
   */
  java.lang.String getColName();
  /**
   * <code>string col_name = 2;</code>
   * @return The bytes for colName.
   */
  com.google.protobuf.ByteString
      getColNameBytes();

  /**
   * <code>string col_type = 3;</code>
   * @return The colType.
   */
  java.lang.String getColType();
  /**
   * <code>string col_type = 3;</code>
   * @return The bytes for colType.
   */
  com.google.protobuf.ByteString
      getColTypeBytes();
}
