// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/common.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adhoc_sdk_v1_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adhoc_sdk_v1_ErrorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020sdk/common.proto\022\014adhoc.sdk.v1\":\n\rErro" +
      "rResponse\022\022\n\nerror_code\030\001 \001(\t\022\025\n\rerror_m" +
      "essage\030\002 \001(\tB*\n&io.gitee.songchaolin.adh" +
      "oc.sdk.grpc.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_adhoc_sdk_v1_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_adhoc_sdk_v1_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adhoc_sdk_v1_ErrorResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
