// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface GetJobStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.GetJobStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 3;</code>
   * @return The error.
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse getError();
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 3;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder();
}
