// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface GetJobResultResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.GetJobResultResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .adhoc.sdk.v1.TaskResult task_results = 1;</code>
   */
  java.util.List<io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskResult> 
      getTaskResultsList();
  /**
   * <code>repeated .adhoc.sdk.v1.TaskResult task_results = 1;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskResult getTaskResults(int index);
  /**
   * <code>repeated .adhoc.sdk.v1.TaskResult task_results = 1;</code>
   */
  int getTaskResultsCount();
  /**
   * <code>repeated .adhoc.sdk.v1.TaskResult task_results = 1;</code>
   */
  java.util.List<? extends io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskResultOrBuilder> 
      getTaskResultsOrBuilderList();
  /**
   * <code>repeated .adhoc.sdk.v1.TaskResult task_results = 1;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskResultOrBuilder getTaskResultsOrBuilder(
      int index);

  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   * @return The error.
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse getError();
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder();
}
