// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface GetJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.GetJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();
}
