// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface GetJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.GetJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string sql_content = 3;</code>
   * @return The sqlContent.
   */
  java.lang.String getSqlContent();
  /**
   * <code>string sql_content = 3;</code>
   * @return The bytes for sqlContent.
   */
  com.google.protobuf.ByteString
      getSqlContentBytes();

  /**
   * <code>string engine_type = 4;</code>
   * @return The engineType.
   */
  java.lang.String getEngineType();
  /**
   * <code>string engine_type = 4;</code>
   * @return The bytes for engineType.
   */
  com.google.protobuf.ByteString
      getEngineTypeBytes();

  /**
   * <pre>
   * epoch millis
   * </pre>
   *
   * <code>int64 submit_time = 5;</code>
   * @return The submitTime.
   */
  long getSubmitTime();

  /**
   * <pre>
   * Task 列表
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.TaskSummary tasks = 6;</code>
   */
  java.util.List<io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary> 
      getTasksList();
  /**
   * <pre>
   * Task 列表
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.TaskSummary tasks = 6;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary getTasks(int index);
  /**
   * <pre>
   * Task 列表
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.TaskSummary tasks = 6;</code>
   */
  int getTasksCount();
  /**
   * <pre>
   * Task 列表
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.TaskSummary tasks = 6;</code>
   */
  java.util.List<? extends io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummaryOrBuilder> 
      getTasksOrBuilderList();
  /**
   * <pre>
   * Task 列表
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.TaskSummary tasks = 6;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummaryOrBuilder getTasksOrBuilder(
      int index);

  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 7;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 7;</code>
   * @return The error.
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse getError();
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 7;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder();
}
