// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface GetTaskResultResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.GetTaskResultResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 列定义
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 1;</code>
   */
  java.util.List<io.gitee.songchaolin.adhoc.sdk.grpc.v1.ColumnSchema> 
      getSchemaList();
  /**
   * <pre>
   * 列定义
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 1;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ColumnSchema getSchema(int index);
  /**
   * <pre>
   * 列定义
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 1;</code>
   */
  int getSchemaCount();
  /**
   * <pre>
   * 列定义
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 1;</code>
   */
  java.util.List<? extends io.gitee.songchaolin.adhoc.sdk.grpc.v1.ColumnSchemaOrBuilder> 
      getSchemaOrBuilderList();
  /**
   * <pre>
   * 列定义
   * </pre>
   *
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 1;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ColumnSchemaOrBuilder getSchemaOrBuilder(
      int index);

  /**
   * <pre>
   * JSON 编码的行
   * </pre>
   *
   * <code>repeated string rows = 2;</code>
   * @return A list containing the rows.
   */
  java.util.List<java.lang.String>
      getRowsList();
  /**
   * <pre>
   * JSON 编码的行
   * </pre>
   *
   * <code>repeated string rows = 2;</code>
   * @return The count of rows.
   */
  int getRowsCount();
  /**
   * <pre>
   * JSON 编码的行
   * </pre>
   *
   * <code>repeated string rows = 2;</code>
   * @param index The index of the element to return.
   * @return The rows at the given index.
   */
  java.lang.String getRows(int index);
  /**
   * <pre>
   * JSON 编码的行
   * </pre>
   *
   * <code>repeated string rows = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the rows at the given index.
   */
  com.google.protobuf.ByteString
      getRowsBytes(int index);

  /**
   * <code>int64 current = 3;</code>
   * @return The current.
   */
  long getCurrent();

  /**
   * <code>int64 size = 4;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>int64 total_rows = 5;</code>
   * @return The totalRows.
   */
  long getTotalRows();

  /**
   * <code>bool has_more = 6;</code>
   * @return The hasMore.
   */
  boolean getHasMore();

  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 7;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 7;</code>
   * @return The error.
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse getError();
  /**
   * <code>.adhoc.sdk.v1.ErrorResponse error = 7;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder();
}
