// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface SubmitJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.SubmitJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Job ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <pre>
   * Job ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   * @return The error.
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponse getError();
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>.adhoc.sdk.v1.ErrorResponse error = 2;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ErrorResponseOrBuilder getErrorOrBuilder();
}
