// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

/**
 * <pre>
 **
 * 提交 Job 请求
 * </pre>
 *
 * Protobuf type {@code adhoc.sdk.v1.SubmitJobRequest}
 */
public final class SubmitJobRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:adhoc.sdk.v1.SubmitJobRequest)
    SubmitJobRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubmitJobRequest.newBuilder() to construct.
  private SubmitJobRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubmitJobRequest() {
    sqlContent_ = "";
    engineType_ = "";
    clientRequestId_ = "";
    fileId_ = "";
    engineInstance_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubmitJobRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_SubmitJobRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_SubmitJobRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest.class, io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest.Builder.class);
  }

  public static final int SQL_CONTENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sqlContent_ = "";
  /**
   * <pre>
   * SQL 原文
   * </pre>
   *
   * <code>string sql_content = 1;</code>
   * @return The sqlContent.
   */
  @java.lang.Override
  public java.lang.String getSqlContent() {
    java.lang.Object ref = sqlContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sqlContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * SQL 原文
   * </pre>
   *
   * <code>string sql_content = 1;</code>
   * @return The bytes for sqlContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSqlContentBytes() {
    java.lang.Object ref = sqlContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sqlContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENGINE_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object engineType_ = "";
  /**
   * <pre>
   * KYUUBI / STARROCKS
   * </pre>
   *
   * <code>string engine_type = 2;</code>
   * @return The engineType.
   */
  @java.lang.Override
  public java.lang.String getEngineType() {
    java.lang.Object ref = engineType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      engineType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * KYUUBI / STARROCKS
   * </pre>
   *
   * <code>string engine_type = 2;</code>
   * @return The bytes for engineType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEngineTypeBytes() {
    java.lang.Object ref = engineType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      engineType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_REQUEST_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientRequestId_ = "";
  /**
   * <pre>
   * 幂等键
   * </pre>
   *
   * <code>string client_request_id = 3;</code>
   * @return The clientRequestId.
   */
  @java.lang.Override
  public java.lang.String getClientRequestId() {
    java.lang.Object ref = clientRequestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientRequestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 幂等键
   * </pre>
   *
   * <code>string client_request_id = 3;</code>
   * @return The bytes for clientRequestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientRequestIdBytes() {
    java.lang.Object ref = clientRequestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientRequestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fileId_ = "";
  /**
   * <pre>
   * 来源文件节点
   * </pre>
   *
   * <code>string file_id = 4;</code>
   * @return The fileId.
   */
  @java.lang.Override
  public java.lang.String getFileId() {
    java.lang.Object ref = fileId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 来源文件节点
   * </pre>
   *
   * <code>string file_id = 4;</code>
   * @return The bytes for fileId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileIdBytes() {
    java.lang.Object ref = fileId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENGINE_INSTANCE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object engineInstance_ = "";
  /**
   * <pre>
   * 引擎实例名（如 kyuubi-02），空则用默认实例
   * </pre>
   *
   * <code>string engine_instance = 5;</code>
   * @return The engineInstance.
   */
  @java.lang.Override
  public java.lang.String getEngineInstance() {
    java.lang.Object ref = engineInstance_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      engineInstance_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 引擎实例名（如 kyuubi-02），空则用默认实例
   * </pre>
   *
   * <code>string engine_instance = 5;</code>
   * @return The bytes for engineInstance.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEngineInstanceBytes() {
    java.lang.Object ref = engineInstance_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      engineInstance_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sqlContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sqlContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engineType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, engineType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientRequestId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientRequestId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fileId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engineInstance_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, engineInstance_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sqlContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sqlContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engineType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, engineType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientRequestId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientRequestId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fileId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engineInstance_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, engineInstance_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest)) {
      return super.equals(obj);
    }
    io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest other = (io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest) obj;

    if (!getSqlContent()
        .equals(other.getSqlContent())) return false;
    if (!getEngineType()
        .equals(other.getEngineType())) return false;
    if (!getClientRequestId()
        .equals(other.getClientRequestId())) return false;
    if (!getFileId()
        .equals(other.getFileId())) return false;
    if (!getEngineInstance()
        .equals(other.getEngineInstance())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SQL_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getSqlContent().hashCode();
    hash = (37 * hash) + ENGINE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEngineType().hashCode();
    hash = (37 * hash) + CLIENT_REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientRequestId().hashCode();
    hash = (37 * hash) + FILE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFileId().hashCode();
    hash = (37 * hash) + ENGINE_INSTANCE_FIELD_NUMBER;
    hash = (53 * hash) + getEngineInstance().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 提交 Job 请求
   * </pre>
   *
   * Protobuf type {@code adhoc.sdk.v1.SubmitJobRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:adhoc.sdk.v1.SubmitJobRequest)
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_SubmitJobRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_SubmitJobRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest.class, io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest.Builder.class);
    }

    // Construct using io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sqlContent_ = "";
      engineType_ = "";
      clientRequestId_ = "";
      fileId_ = "";
      engineInstance_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_SubmitJobRequest_descriptor;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest getDefaultInstanceForType() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest build() {
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest buildPartial() {
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest result = new io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sqlContent_ = sqlContent_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.engineType_ = engineType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.clientRequestId_ = clientRequestId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fileId_ = fileId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.engineInstance_ = engineInstance_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest) {
        return mergeFrom((io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest other) {
      if (other == io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest.getDefaultInstance()) return this;
      if (!other.getSqlContent().isEmpty()) {
        sqlContent_ = other.sqlContent_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getEngineType().isEmpty()) {
        engineType_ = other.engineType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getClientRequestId().isEmpty()) {
        clientRequestId_ = other.clientRequestId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getFileId().isEmpty()) {
        fileId_ = other.fileId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getEngineInstance().isEmpty()) {
        engineInstance_ = other.engineInstance_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sqlContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              engineType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              clientRequestId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              fileId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              engineInstance_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sqlContent_ = "";
    /**
     * <pre>
     * SQL 原文
     * </pre>
     *
     * <code>string sql_content = 1;</code>
     * @return The sqlContent.
     */
    public java.lang.String getSqlContent() {
      java.lang.Object ref = sqlContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sqlContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * SQL 原文
     * </pre>
     *
     * <code>string sql_content = 1;</code>
     * @return The bytes for sqlContent.
     */
    public com.google.protobuf.ByteString
        getSqlContentBytes() {
      java.lang.Object ref = sqlContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * SQL 原文
     * </pre>
     *
     * <code>string sql_content = 1;</code>
     * @param value The sqlContent to set.
     * @return This builder for chaining.
     */
    public Builder setSqlContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sqlContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL 原文
     * </pre>
     *
     * <code>string sql_content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSqlContent() {
      sqlContent_ = getDefaultInstance().getSqlContent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL 原文
     * </pre>
     *
     * <code>string sql_content = 1;</code>
     * @param value The bytes for sqlContent to set.
     * @return This builder for chaining.
     */
    public Builder setSqlContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sqlContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object engineType_ = "";
    /**
     * <pre>
     * KYUUBI / STARROCKS
     * </pre>
     *
     * <code>string engine_type = 2;</code>
     * @return The engineType.
     */
    public java.lang.String getEngineType() {
      java.lang.Object ref = engineType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engineType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * KYUUBI / STARROCKS
     * </pre>
     *
     * <code>string engine_type = 2;</code>
     * @return The bytes for engineType.
     */
    public com.google.protobuf.ByteString
        getEngineTypeBytes() {
      java.lang.Object ref = engineType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * KYUUBI / STARROCKS
     * </pre>
     *
     * <code>string engine_type = 2;</code>
     * @param value The engineType to set.
     * @return This builder for chaining.
     */
    public Builder setEngineType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      engineType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KYUUBI / STARROCKS
     * </pre>
     *
     * <code>string engine_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEngineType() {
      engineType_ = getDefaultInstance().getEngineType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KYUUBI / STARROCKS
     * </pre>
     *
     * <code>string engine_type = 2;</code>
     * @param value The bytes for engineType to set.
     * @return This builder for chaining.
     */
    public Builder setEngineTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      engineType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object clientRequestId_ = "";
    /**
     * <pre>
     * 幂等键
     * </pre>
     *
     * <code>string client_request_id = 3;</code>
     * @return The clientRequestId.
     */
    public java.lang.String getClientRequestId() {
      java.lang.Object ref = clientRequestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientRequestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 幂等键
     * </pre>
     *
     * <code>string client_request_id = 3;</code>
     * @return The bytes for clientRequestId.
     */
    public com.google.protobuf.ByteString
        getClientRequestIdBytes() {
      java.lang.Object ref = clientRequestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientRequestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 幂等键
     * </pre>
     *
     * <code>string client_request_id = 3;</code>
     * @param value The clientRequestId to set.
     * @return This builder for chaining.
     */
    public Builder setClientRequestId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientRequestId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 幂等键
     * </pre>
     *
     * <code>string client_request_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientRequestId() {
      clientRequestId_ = getDefaultInstance().getClientRequestId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 幂等键
     * </pre>
     *
     * <code>string client_request_id = 3;</code>
     * @param value The bytes for clientRequestId to set.
     * @return This builder for chaining.
     */
    public Builder setClientRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientRequestId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object fileId_ = "";
    /**
     * <pre>
     * 来源文件节点
     * </pre>
     *
     * <code>string file_id = 4;</code>
     * @return The fileId.
     */
    public java.lang.String getFileId() {
      java.lang.Object ref = fileId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 来源文件节点
     * </pre>
     *
     * <code>string file_id = 4;</code>
     * @return The bytes for fileId.
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      java.lang.Object ref = fileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 来源文件节点
     * </pre>
     *
     * <code>string file_id = 4;</code>
     * @param value The fileId to set.
     * @return This builder for chaining.
     */
    public Builder setFileId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fileId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 来源文件节点
     * </pre>
     *
     * <code>string file_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileId() {
      fileId_ = getDefaultInstance().getFileId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 来源文件节点
     * </pre>
     *
     * <code>string file_id = 4;</code>
     * @param value The bytes for fileId to set.
     * @return This builder for chaining.
     */
    public Builder setFileIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object engineInstance_ = "";
    /**
     * <pre>
     * 引擎实例名（如 kyuubi-02），空则用默认实例
     * </pre>
     *
     * <code>string engine_instance = 5;</code>
     * @return The engineInstance.
     */
    public java.lang.String getEngineInstance() {
      java.lang.Object ref = engineInstance_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engineInstance_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 引擎实例名（如 kyuubi-02），空则用默认实例
     * </pre>
     *
     * <code>string engine_instance = 5;</code>
     * @return The bytes for engineInstance.
     */
    public com.google.protobuf.ByteString
        getEngineInstanceBytes() {
      java.lang.Object ref = engineInstance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineInstance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 引擎实例名（如 kyuubi-02），空则用默认实例
     * </pre>
     *
     * <code>string engine_instance = 5;</code>
     * @param value The engineInstance to set.
     * @return This builder for chaining.
     */
    public Builder setEngineInstance(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      engineInstance_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引擎实例名（如 kyuubi-02），空则用默认实例
     * </pre>
     *
     * <code>string engine_instance = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEngineInstance() {
      engineInstance_ = getDefaultInstance().getEngineInstance();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引擎实例名（如 kyuubi-02），空则用默认实例
     * </pre>
     *
     * <code>string engine_instance = 5;</code>
     * @param value The bytes for engineInstance to set.
     * @return This builder for chaining.
     */
    public Builder setEngineInstanceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      engineInstance_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:adhoc.sdk.v1.SubmitJobRequest)
  }

  // @@protoc_insertion_point(class_scope:adhoc.sdk.v1.SubmitJobRequest)
  private static final io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest();
  }

  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubmitJobRequest>
      PARSER = new com.google.protobuf.AbstractParser<SubmitJobRequest>() {
    @java.lang.Override
    public SubmitJobRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubmitJobRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubmitJobRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.gitee.songchaolin.adhoc.sdk.grpc.v1.SubmitJobRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

