// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

/**
 * <pre>
 **
 * Task 摘要信息
 * </pre>
 *
 * Protobuf type {@code adhoc.sdk.v1.TaskSummary}
 */
public final class TaskSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:adhoc.sdk.v1.TaskSummary)
    TaskSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskSummary.newBuilder() to construct.
  private TaskSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskSummary() {
    taskId_ = "";
    sqlContent_ = "";
    sqlType_ = "";
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TaskSummary();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_TaskSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_TaskSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary.class, io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary.Builder.class);
  }

  public static final int TASK_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object taskId_ = "";
  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEGMENT_INDEX_FIELD_NUMBER = 2;
  private int segmentIndex_ = 0;
  /**
   * <code>int32 segment_index = 2;</code>
   * @return The segmentIndex.
   */
  @java.lang.Override
  public int getSegmentIndex() {
    return segmentIndex_;
  }

  public static final int SQL_CONTENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sqlContent_ = "";
  /**
   * <code>string sql_content = 3;</code>
   * @return The sqlContent.
   */
  @java.lang.Override
  public java.lang.String getSqlContent() {
    java.lang.Object ref = sqlContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sqlContent_ = s;
      return s;
    }
  }
  /**
   * <code>string sql_content = 3;</code>
   * @return The bytes for sqlContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSqlContentBytes() {
    java.lang.Object ref = sqlContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sqlContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SQL_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sqlType_ = "";
  /**
   * <code>string sql_type = 4;</code>
   * @return The sqlType.
   */
  @java.lang.Override
  public java.lang.String getSqlType() {
    java.lang.Object ref = sqlType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sqlType_ = s;
      return s;
    }
  }
  /**
   * <code>string sql_type = 4;</code>
   * @return The bytes for sqlType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSqlTypeBytes() {
    java.lang.Object ref = sqlType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sqlType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_ROWS_FIELD_NUMBER = 6;
  private long resultRows_ = 0L;
  /**
   * <code>int64 result_rows = 6;</code>
   * @return The resultRows.
   */
  @java.lang.Override
  public long getResultRows() {
    return resultRows_;
  }

  public static final int RESULT_BYTES_FIELD_NUMBER = 7;
  private long resultBytes_ = 0L;
  /**
   * <code>int64 result_bytes = 7;</code>
   * @return The resultBytes.
   */
  @java.lang.Override
  public long getResultBytes() {
    return resultBytes_;
  }

  public static final int HAS_RESULT_SET_FIELD_NUMBER = 8;
  private boolean hasResultSet_ = false;
  /**
   * <pre>
   * 是否有结果集
   * </pre>
   *
   * <code>bool has_result_set = 8;</code>
   * @return The hasResultSet.
   */
  @java.lang.Override
  public boolean getHasResultSet() {
    return hasResultSet_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
    }
    if (segmentIndex_ != 0) {
      output.writeInt32(2, segmentIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sqlContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sqlContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sqlType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sqlType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, status_);
    }
    if (resultRows_ != 0L) {
      output.writeInt64(6, resultRows_);
    }
    if (resultBytes_ != 0L) {
      output.writeInt64(7, resultBytes_);
    }
    if (hasResultSet_ != false) {
      output.writeBool(8, hasResultSet_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
    }
    if (segmentIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, segmentIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sqlContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sqlContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sqlType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sqlType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, status_);
    }
    if (resultRows_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, resultRows_);
    }
    if (resultBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, resultBytes_);
    }
    if (hasResultSet_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, hasResultSet_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary)) {
      return super.equals(obj);
    }
    io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary other = (io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary) obj;

    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (getSegmentIndex()
        != other.getSegmentIndex()) return false;
    if (!getSqlContent()
        .equals(other.getSqlContent())) return false;
    if (!getSqlType()
        .equals(other.getSqlType())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (getResultRows()
        != other.getResultRows()) return false;
    if (getResultBytes()
        != other.getResultBytes()) return false;
    if (getHasResultSet()
        != other.getHasResultSet()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + SEGMENT_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getSegmentIndex();
    hash = (37 * hash) + SQL_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getSqlContent().hashCode();
    hash = (37 * hash) + SQL_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSqlType().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + RESULT_ROWS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getResultRows());
    hash = (37 * hash) + RESULT_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getResultBytes());
    hash = (37 * hash) + HAS_RESULT_SET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasResultSet());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Task 摘要信息
   * </pre>
   *
   * Protobuf type {@code adhoc.sdk.v1.TaskSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:adhoc.sdk.v1.TaskSummary)
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_TaskSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_TaskSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary.class, io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary.Builder.class);
    }

    // Construct using io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      taskId_ = "";
      segmentIndex_ = 0;
      sqlContent_ = "";
      sqlType_ = "";
      status_ = "";
      resultRows_ = 0L;
      resultBytes_ = 0L;
      hasResultSet_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.AdhocServiceOuterClass.internal_static_adhoc_sdk_v1_TaskSummary_descriptor;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary getDefaultInstanceForType() {
      return io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary.getDefaultInstance();
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary build() {
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary buildPartial() {
      io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary result = new io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.taskId_ = taskId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.segmentIndex_ = segmentIndex_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sqlContent_ = sqlContent_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sqlType_ = sqlType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.resultRows_ = resultRows_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.resultBytes_ = resultBytes_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.hasResultSet_ = hasResultSet_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary) {
        return mergeFrom((io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary other) {
      if (other == io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary.getDefaultInstance()) return this;
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getSegmentIndex() != 0) {
        setSegmentIndex(other.getSegmentIndex());
      }
      if (!other.getSqlContent().isEmpty()) {
        sqlContent_ = other.sqlContent_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSqlType().isEmpty()) {
        sqlType_ = other.sqlType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getResultRows() != 0L) {
        setResultRows(other.getResultRows());
      }
      if (other.getResultBytes() != 0L) {
        setResultBytes(other.getResultBytes());
      }
      if (other.getHasResultSet() != false) {
        setHasResultSet(other.getHasResultSet());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              taskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              segmentIndex_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              sqlContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sqlType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              resultRows_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              resultBytes_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              hasResultSet_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object taskId_ = "";
    /**
     * <code>string task_id = 1;</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_id = 1;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      taskId_ = getDefaultInstance().getTaskId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 1;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int segmentIndex_ ;
    /**
     * <code>int32 segment_index = 2;</code>
     * @return The segmentIndex.
     */
    @java.lang.Override
    public int getSegmentIndex() {
      return segmentIndex_;
    }
    /**
     * <code>int32 segment_index = 2;</code>
     * @param value The segmentIndex to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentIndex(int value) {

      segmentIndex_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 segment_index = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSegmentIndex() {
      bitField0_ = (bitField0_ & ~0x00000002);
      segmentIndex_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sqlContent_ = "";
    /**
     * <code>string sql_content = 3;</code>
     * @return The sqlContent.
     */
    public java.lang.String getSqlContent() {
      java.lang.Object ref = sqlContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sqlContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sql_content = 3;</code>
     * @return The bytes for sqlContent.
     */
    public com.google.protobuf.ByteString
        getSqlContentBytes() {
      java.lang.Object ref = sqlContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sql_content = 3;</code>
     * @param value The sqlContent to set.
     * @return This builder for chaining.
     */
    public Builder setSqlContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sqlContent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string sql_content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSqlContent() {
      sqlContent_ = getDefaultInstance().getSqlContent();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string sql_content = 3;</code>
     * @param value The bytes for sqlContent to set.
     * @return This builder for chaining.
     */
    public Builder setSqlContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sqlContent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object sqlType_ = "";
    /**
     * <code>string sql_type = 4;</code>
     * @return The sqlType.
     */
    public java.lang.String getSqlType() {
      java.lang.Object ref = sqlType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sqlType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sql_type = 4;</code>
     * @return The bytes for sqlType.
     */
    public com.google.protobuf.ByteString
        getSqlTypeBytes() {
      java.lang.Object ref = sqlType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sql_type = 4;</code>
     * @param value The sqlType to set.
     * @return This builder for chaining.
     */
    public Builder setSqlType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sqlType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string sql_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSqlType() {
      sqlType_ = getDefaultInstance().getSqlType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string sql_type = 4;</code>
     * @param value The bytes for sqlType to set.
     * @return This builder for chaining.
     */
    public Builder setSqlTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sqlType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 5;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long resultRows_ ;
    /**
     * <code>int64 result_rows = 6;</code>
     * @return The resultRows.
     */
    @java.lang.Override
    public long getResultRows() {
      return resultRows_;
    }
    /**
     * <code>int64 result_rows = 6;</code>
     * @param value The resultRows to set.
     * @return This builder for chaining.
     */
    public Builder setResultRows(long value) {

      resultRows_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 result_rows = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultRows() {
      bitField0_ = (bitField0_ & ~0x00000020);
      resultRows_ = 0L;
      onChanged();
      return this;
    }

    private long resultBytes_ ;
    /**
     * <code>int64 result_bytes = 7;</code>
     * @return The resultBytes.
     */
    @java.lang.Override
    public long getResultBytes() {
      return resultBytes_;
    }
    /**
     * <code>int64 result_bytes = 7;</code>
     * @param value The resultBytes to set.
     * @return This builder for chaining.
     */
    public Builder setResultBytes(long value) {

      resultBytes_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 result_bytes = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultBytes() {
      bitField0_ = (bitField0_ & ~0x00000040);
      resultBytes_ = 0L;
      onChanged();
      return this;
    }

    private boolean hasResultSet_ ;
    /**
     * <pre>
     * 是否有结果集
     * </pre>
     *
     * <code>bool has_result_set = 8;</code>
     * @return The hasResultSet.
     */
    @java.lang.Override
    public boolean getHasResultSet() {
      return hasResultSet_;
    }
    /**
     * <pre>
     * 是否有结果集
     * </pre>
     *
     * <code>bool has_result_set = 8;</code>
     * @param value The hasResultSet to set.
     * @return This builder for chaining.
     */
    public Builder setHasResultSet(boolean value) {

      hasResultSet_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否有结果集
     * </pre>
     *
     * <code>bool has_result_set = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasResultSet() {
      bitField0_ = (bitField0_ & ~0x00000080);
      hasResultSet_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:adhoc.sdk.v1.TaskSummary)
  }

  // @@protoc_insertion_point(class_scope:adhoc.sdk.v1.TaskSummary)
  private static final io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary();
  }

  public static io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskSummary>
      PARSER = new com.google.protobuf.AbstractParser<TaskSummary>() {
    @java.lang.Override
    public TaskSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TaskSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.gitee.songchaolin.adhoc.sdk.grpc.v1.TaskSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

