// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface TaskResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.TaskResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>int32 segment_index = 2;</code>
   * @return The segmentIndex.
   */
  int getSegmentIndex();

  /**
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 3;</code>
   */
  java.util.List<io.gitee.songchaolin.adhoc.sdk.grpc.v1.ColumnSchema> 
      getSchemaList();
  /**
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 3;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ColumnSchema getSchema(int index);
  /**
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 3;</code>
   */
  int getSchemaCount();
  /**
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 3;</code>
   */
  java.util.List<? extends io.gitee.songchaolin.adhoc.sdk.grpc.v1.ColumnSchemaOrBuilder> 
      getSchemaOrBuilderList();
  /**
   * <code>repeated .adhoc.sdk.v1.ColumnSchema schema = 3;</code>
   */
  io.gitee.songchaolin.adhoc.sdk.grpc.v1.ColumnSchemaOrBuilder getSchemaOrBuilder(
      int index);

  /**
   * <code>repeated string rows = 4;</code>
   * @return A list containing the rows.
   */
  java.util.List<java.lang.String>
      getRowsList();
  /**
   * <code>repeated string rows = 4;</code>
   * @return The count of rows.
   */
  int getRowsCount();
  /**
   * <code>repeated string rows = 4;</code>
   * @param index The index of the element to return.
   * @return The rows at the given index.
   */
  java.lang.String getRows(int index);
  /**
   * <code>repeated string rows = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the rows at the given index.
   */
  com.google.protobuf.ByteString
      getRowsBytes(int index);

  /**
   * <code>int64 total_rows = 5;</code>
   * @return The totalRows.
   */
  long getTotalRows();

  /**
   * <code>bool has_more = 6;</code>
   * @return The hasMore.
   */
  boolean getHasMore();
}
