// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/adhoc_service.proto

package io.gitee.songchaolin.adhoc.sdk.grpc.v1;

public interface TaskSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adhoc.sdk.v1.TaskSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>int32 segment_index = 2;</code>
   * @return The segmentIndex.
   */
  int getSegmentIndex();

  /**
   * <code>string sql_content = 3;</code>
   * @return The sqlContent.
   */
  java.lang.String getSqlContent();
  /**
   * <code>string sql_content = 3;</code>
   * @return The bytes for sqlContent.
   */
  com.google.protobuf.ByteString
      getSqlContentBytes();

  /**
   * <code>string sql_type = 4;</code>
   * @return The sqlType.
   */
  java.lang.String getSqlType();
  /**
   * <code>string sql_type = 4;</code>
   * @return The bytes for sqlType.
   */
  com.google.protobuf.ByteString
      getSqlTypeBytes();

  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int64 result_rows = 6;</code>
   * @return The resultRows.
   */
  long getResultRows();

  /**
   * <code>int64 result_bytes = 7;</code>
   * @return The resultBytes.
   */
  long getResultBytes();

  /**
   * <pre>
   * 是否有结果集
   * </pre>
   *
   * <code>bool has_result_set = 8;</code>
   * @return The hasResultSet.
   */
  boolean getHasResultSet();
}
